# Generated by Django 5.2.17 on 2026-08-27 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_id',
            field=models.ForeignKey(blank=True, help_text='Links an employee to their admin manager; null for admin accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, default='', help_text='Installed application version.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='connect_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated unique code for admin accounts (e.g. OBL-XXXX-XXXX).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Indicates whether the employee has acknowledged the monitoring disclosure.'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_model',
            field=models.CharField(blank=True, default='', help_text='Hardware device model (e.g. Samsung Galaxy S24, Pixel 8).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text="Unique identifier for the employee's company-issued Android device.", max_length=255, null=True),
        ),
    ]
