# Generated by Django 5.2.4 on 2026-09-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_admin_id_user_app_version_user_connect_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='connect_code',
        ),
    ]
